run: segment-tree-efficient.cpp
	g++ -std=c++17 segment-tree-efficient.cpp -o trial
	./trial 
	rm trial

run1: segment-tree-lazy-propogation.cpp
	g++ -std=c++17 segment-tree-lazy-propogation.cpp -o trial
	./trial < t.txt
	rm trial
